#!/usr/bin/env python3

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from ctypes import *

libtkp = CDLL("../src/libtkp.so")

encode_str = libtkp.encode_str
encode_str.restype = c_size_t
encode_str.argtypes = [c_char_p, c_char_p, c_size_t]

decode_str = libtkp.decode_str
decode_str.restype = c_size_t
decode_str.argtypes = [c_char_p, c_char_p, c_size_t]

test_str = "Nobody expects the Spanish Inquisition.,"
test_str_len = len(test_str)

test_string = create_string_buffer(test_str.encode('ascii'))

encoded_len = ((3 * test_str_len) + 3) // 4 # round up calculation to get required length
encoded_str = create_string_buffer(encoded_len)
encode_str(test_string, encoded_str, c_size_t(encoded_len))

print(encoded_str.raw)

decoded_len = ((4 * encoded_len) + 2) // 3 # round up calculation to get required length
decoded_str = create_string_buffer(decoded_len)

decode_str(encoded_str, decoded_str, test_str_len)
# print(decoded_str)
print(decoded_str.raw)
print(decoded_str.raw.decode('utf-8'))